Update README build section copy for clarity
MFEK/glif pull request #230
Opened 2022-01-02 16:35 UTC by eliheuer

This fixes issue https://github.com/MFEK/glif/issues/229

I moved some things around in the README for clarity:

- The suggestion to install the Vulkan SDK was moved from the "mac" section to the "for everyone" section.
- The "for everyone" section was moved to the top of the "build" section, because it's instructions should be read and done first IMO.

2022-01-03 08:10 UTC, ctrlcctrlv requested changes

2022-01-03 08:10 UTC, ctrlcctrlv commented on README.md
> +* Download and install the [Vulkan SDK](https://vulkan.lunarg.com/).
https://github.com/MFEK/glif/issues/229#issuecomment-1003817820
>  I believe you would've been able to compile in release mode just fine without the Vulkan SDK, so am not sure about the wording of your PR.

2022-01-04 01:39 UTC, eliheuer commented on README.md
> +* Download and install the [Vulkan SDK](https://vulkan.lunarg.com/).
Ok, Thanks! I just tested this and `cargo run --release .../A_.glif` works without the Vulkan SDK installed, but `cargo run .../A_.glif` gets the first build error for that issue.

2022-01-04 06:49 UTC, ctrlcctrlv commented
Reopening as an issue to track confusing docs.

2022-01-04 06:58 UTC, closed without merging