Add Nix flake support
MFEK/glif pull request #370
Opened 2022-12-24 21:04 UTC by jakeisnt

This helps anyone who uses `NixOS` or `nix` get started with a development environment seamlessly. If someone has `nix` and `direnv` installed, upon entering this repository they'll have a development environment with the exact versions of rust and all of the system packages necessary to build the repo.

It:
- Exposes a development shell with all system and rust dependencies configured
- Adds a `glif-test` command adhering to the suggested `cargo run` command in the README for testing the package
-  Enables nix builds of the `glif` package, which can then be pulled into other packages

Put this together to get glif to run on my end; merge if others would use, OK to close if not.

2022-12-24 21:07 UTC, ctrlcctrlv requested changes
Thanks for the very long contribution. I've used nix before but barely, I just used it as some package required it so I don't know how to test this but assume it works.

However I think this ought to also build (at least) MFEKmetadata, MFEKstroke, MFEKpathops, MFEKinit. They're all a lot simpler to build. Some functions will _not_ work if MFEKmetadata is not installed. MFEKinit is very useful for making initial .glif files.

2022-12-24 21:08 UTC, ctrlcctrlv commented
If you do this then probably these files belong in a new repo, MFEK/flake.nix. I can create it for you and leave it empty if you want me to.

2022-12-24 21:11 UTC, ctrlcctrlv commented
Oh and last thought. MFEK's IPC uses `--version` and `$PATH` only to find its fellow modules so there's nothing special you have to do besides put all those binaries in the NixOS `$PATH`.

2022-12-24 21:39 UTC, alerque commented
I would suggest a flake in each of those other repositories, then depend on them from the flake in this repository. Having a "parking" repository just for a combined flake kind of defeats the purpose and expected usage.

2022-12-24 21:55 UTC, ctrlcctrlv commented
Oh, I see. Well, I still think a parking repository makes sense, as even though this is the org's most popular project, it's not the "root" module in any sense. You can use MFEKstroke / MFEKpathops / MFEKmetadata without it just fine.

But perhaps that actually makes this easier for @jakeisnt. If he adds a flake to MFEKmetadata, and makes this rely on that, I'll consider that enough to merge this. (That's the only IPC-checked dependency at current.)

2022-12-24 21:56 UTC, jakeisnt commented
On it!

2022-12-24 21:58 UTC, ctrlcctrlv commented
Thanks! Sorry for my ignorance of NixOS :-)

If there's enough interest I'll make MFEK/flake.nix myself after merging this and the MFEKmetadata PR.

2022-12-24 21:59 UTC, ctrlcctrlv requested changes

2022-12-24 21:59 UTC, ctrlcctrlv commented on flake.nix
> +  name = "glif";
Name should be "MFEKglif"

2022-12-24 21:59 UTC, ctrlcctrlv commented on flake.nix
> +  description = "glyph editor";
```suggestion
  description = "Glyph editor for the Modular Font Editor K project.";
```

2022-12-25 02:03 UTC, ctrlcctrlv commented
> Agree that the flake-per-repo approach is more reasonable, as it allows developers to make use of nix shell environments.

Do you think that the idea of having an MFEK/flake.nix with all the binary tools isn't useful then?

The best supported installation method, if you can even call it one, is basically that:

https://github.com/MFEK/docs/blob/8eb89d4c2217969900e7708dab1585d549e7ac26/blob/pull_all_modules.sh

2022-12-26 21:14 UTC, ctrlcctrlv commented
Marked as draft as blocked on https://github.com/MFEK/metadata/pull/139#issuecomment-1364631789 (see subsequent comment on potential fix).

2025-05-13 11:17 UTC, jakeisnt commented
wontfix

2025-05-13 11:17 UTC, closed without merging